### ISSUE TITLE
ggsankey vs ggalluvial

### ISSUE THREAD

**Issue by dariober** [davidsjoberg/ggsankey#20]
Hi- I just discovered the existence of Sankey plots (or rather, that such things had a name and could be done in R...). 

I found your package and ggalluvial, which seems to pre-date ggsankey. Can you comment on the pros and cons of ggsankey? Both packages seem pretty good at a first glance. Thanks!

**Comment by davidsjoberg** [comment]
Hi!

You should probably ask someone else for an unbiased opinion. But here I go.

to my experience ggallivial is much more mature and well maintained, and you should probably use that. One reason to use ggsankey could maybe be that, if I understand it correctly, ggalluvial doesn’t allow sankey plots that’s centered around the x axis and have space between nodes. Also there is a difference in API that one might have a preference about.

hope that helps!
