### ISSUE TITLE
size of the flow

### ISSUE THREAD

**Issue by dmongin** [davidsjoberg/ggsankey#6]
Is there a way in `geom_sankey` to specify an aesthetic that provides directly the size of the flow, i.e. the number of connections between the nodes?

For example:

```
df <- data.frame(expand.grid(LETTERS[1:3],LETTERS[1:3]))
df$N <- sample(1:10,size = nrow(df),replace = T)
```

I would like something like

```
df %>%
make_long(Var1, Var2)%>%
  ggplot( aes(x = x, 
                 next_x = next_x, 
                 node = node, 
                 next_node = next_node,
                 fill = factor(node))) +
  geom_sankey()
```
![image](https://user-images.githubusercontent.com/19406581/119405600-cbee7d00-bce1-11eb-8472-d8a26272f5d2.png)

But with the flows given by `N`. A hack would be to repeat each row by N before the `make_long`, but I am sure there is a proper way.

**Comment by davidsjoberg** [comment]
Thanks for your issue! I have added the argument `value` to make long so that it also creates a weight column to be passed to `ggsankey` where the aesthetic `values` can be used. Reinstall ggsankey and try this reprex:

``` r
library(tidyverse)
library(ggsankey)

df <- data.frame(expand.grid(LETTERS[1:3],LETTERS[1:3]))
df$N <- sample(1:10,size = nrow(df),replace = T)
df <- df %>% 
  make_long(Var1, Var2, value = N)

df %>%
  ggplot( aes(x = x,
              next_x = next_x,
              node = node,
              next_node = next_node,
              fill = factor(node),
              value = value)) +
  geom_sankey()
```

![](https://i.imgur.com/UEPcycb.png)

<sup>Created on 2021-05-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dmongin** [comment]
Whaou, perfect. Thank you for your reactivity and your work!

**Comment by matteloca** [comment]
Great!
How can I plot the values? Like under Node.

df %>%
  ggplot( aes(x = x,
              next_x = next_x,
              node = node,
              next_node = next_node,
              fill = factor(node),
              value = value,
               label = paste0(node,'\n',value)) + #doesn't work
  geom_sankey()
